spring.profiles.active=mysql-local-docker
security.basic.enabled=false
spring.jackson.date-format=com.fasterxml.jackson.databind.util.ISO8601DateFormat

#AWS SES PROPERTIES
aws.ses.access.key=SES_ACCESS_KEY
aws.ses.secret.key=SES_SECRET_KEY
aws.ses.region=us-east-1
aws.mail.sender=mdd@cmlatitude.com

#AWS SNSPROPERTIES
aws.sns.access.key=SNS_ACCESS_KEY
aws.sns.secret.key=SNS_SECRET_KEY
aws.sns.region=us-east-1
aws.sms.sender=MDD

#QUERY PROPERTIES
query.pagination.default.page=0
query.pagination.default.per.page=50
#FILE UPLOAD LIMITS
spring.http.multipart.max-file-size=5MB
spring.http.multipart.max-request-size=5MB
#FOR URLs TO MDD application
#TODO UPDATE THE LINK TO DEFAULT VALUE OF MDD PORTAL WHEN IT WILL BE KNOWN, UP TO THAT MOMENT USING LOCALHOST
mdd.domain=http://localhost:8080
mdd.registration.complete.relative.hyperlink=/#/signup/activate
mdd.reset.password.relative.hyperlink=/#/account/reset
mdd.change.username.relative.hyperlink=/#/account/username

#GOOGLE GEOCODING
google.geocoding.api.key=AIzaSyDCxUEEDM8KtYo80kj1hNBVDfIA7r63gLM
google.geocoding.api.url=https://maps.googleapis.com/maps/api/geocode/json?address={zipCode}&key=${google.geocoding.api.key}

system.super.user.id=fb409241-68a5-47cd-a379-e356ce403dc0

job.scheduling.enabled=true
# Fix the warning with Jaxb1 properties
server.tomcat.additional-tld-skip-patterns=*.jar
#=derbyLocale_*.jar,jaxb-api.jar,jsr173_1.0_api.jar,jaxb1-impl.jar,activation.jar
# IDs of categories - should be updated if id is updated in database
specialties.dds.id=DENTISTS
specialties.rdh.id=HYGIENISTS
specialties.rda.id=ASSISTANTS
specialties.frontoffice.id=FRONT_OFFICE_PERSONNEL
#JASPER REPORT SERVER
#Authentication & target folder
jasper.report.server.username=mfd-mdd
jasper.report.server.password=Adm12JRSroo!
jasper.report.server.repositoryReportFolderUri=/mfd_mdd/reports/deployed/mdd_qa_test
#Rest Client
jasper.report.server.client.url=http://jasper-reports.cmlatitude.com
jasper.report.server.client.connectionTimeout=180000
jasper.report.server.client.readTimeout=180000
jasper.report.server.client.jasperserverVersion=v6_1_0
jasper.report.server.client.authenticationType=SPRING
jasper.report.server.client.logHttp=true
jasper.report.server.client.logHttpEntity=true
jasper.report.server.client.restrictedHttpMethods=false
jasper.report.server.client.handleErrors=true
jasper.report.server.client.contentMimeType=JSON
jasper.report.server.client.acceptMimeType=JSON