#spring.datasource.type=org.apache.commons.dbcp2.BasicDataSource
spring.datasource.url=jdbc:mysql://
spring.datasource.username=
spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.datasource.dbcp2.validation-query=select 1

flyway.locations=classpath:db/migration/mysql
#FILE UPLOAD LIMITS
spring.http.multipart.max-file-size=5MB
spring.http.multipart.max-request-size=5MB
#FOR URLs TO MDD application
mdd.domain=http://localhost:8080
mdd.registration.complete.relative.hyperlink=/#/signup/activate
mdd.reset.password.relative.hyperlink=/#/account/reset
mdd.change.username.relative.hyperlink=/#/account/username