#spring.datasource.type=org.apache.commons.dbcp2.BasicDataSource
spring.datasource.url=jdbc:mysql://mdd-mysql:3306/mdd?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=mdd
spring.datasource.password=mdd
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.datasource.dbcp2.validation-query=select 1
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true

# DB
flyway.baselineOnMigrate=true
flyway.locations=classpath:db/migration/mysql

security.cookies.secure=false
security.cookies.httpOnly=false
security.csrf.protection.enabled=false
#FILE UPLOAD LIMITS
spring.http.multipart.max-file-size=5MB
spring.http.multipart.max-request-size=5MB

#FOR URLs TO MDD application
mdd.domain=http://localhost:8080
mdd.registration.complete.relative.hyperlink=/#/signup/activate
mdd.reset.password.relative.hyperlink=/#/account/reset
mdd.change.username.relative.hyperlink=/#/account/username
exception.resolvers.show.stacktrace=true
#JASPER REPORT SERVER
#Authentication & target folder
jasper.report.server.username=mfd-mdd
jasper.report.server.password=Adm12JRSroo!
jasper.report.server.repositoryReportFolderUri=/mfd_mdd/reports/deployed/mdd_qa_test/
#Rest Client
jasper.report.server.client.url=http://jasper-reports.cmlatitude.com
jasper.report.server.client.connectionTimeout=180000
jasper.report.server.client.readTimeout=180000
jasper.report.server.client.jasperserverVersion=v6_1_0
jasper.report.server.client.authenticationType=SPRING
jasper.report.server.client.logHttp=true
jasper.report.server.client.logHttpEntity=true
jasper.report.server.client.restrictedHttpMethods=false
jasper.report.server.client.handleErrors=true
jasper.report.server.client.contentMimeType=JSON
jasper.report.server.client.acceptMimeType=JSON
job.posting.publish.payment.method.optional=true