spring.datasource.url=jdbc:hsqldb:file:${basedir}/target/test-classes/mdd.db;shutdown=true
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.hsqldb.jdbcDriver
spring.jpa.hibernate.ddl-auto=create

flyway.locations=classpath:db/migration/hsqldb
#FILE UPLOAD LIMITS
spring.http.multipart.max-file-size=5MB
spring.http.multipart.max-request-size=5MB
#FOR URLs TO MDD application
mdd.domain=http://localhost:8080
mdd.registration.complete.relative.hyperlink=/#/signup/activate
mdd.reset.password.relative.hyperlink=/#/account/reset
mdd.change.username.relative.hyperlink=/#/account/username
aws.mail.sender=mdd@cmlatitude.com
exception.resolvers.show.stacktrace=true