/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfessionalRouteImport } from './routes/professional'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfessionalIndexRouteImport } from './routes/professional.index'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProfessionalTemporaryJobsRouteImport } from './routes/professional.temporary-jobs'
import { Route as ProfessionalSpecialtiesRouteImport } from './routes/professional.specialties'
import { Route as ProfessionalSkillsRouteImport } from './routes/professional.skills'
import { Route as ProfessionalProfileRouteImport } from './routes/professional.profile'
import { Route as ProfessionalPermanentJobsRouteImport } from './routes/professional.permanent-jobs'
import { Route as ProfessionalJobHistoryRouteImport } from './routes/professional.job-history'
import { Route as ProfessionalDocumentsRouteImport } from './routes/professional.documents'
import { Route as ProfessionalCertificatesRouteImport } from './routes/professional.certificates'
import { Route as ProfessionalBannedOfficesRouteImport } from './routes/professional.banned-offices'
import { Route as PracticeStaffRouteImport } from './routes/practice.staff'
import { Route as PracticeSettingsRouteImport } from './routes/practice.settings'
import { Route as PracticeScheduleRouteImport } from './routes/practice.schedule'
import { Route as PracticePostingsRouteImport } from './routes/practice.postings'
import { Route as PracticeBillingRouteImport } from './routes/practice.billing'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'

const ProfessionalRoute = ProfessionalRouteImport.update({
  id: '/professional',
  path: '/professional',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalIndexRoute = ProfessionalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfessionalRoute,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfessionalTemporaryJobsRoute =
  ProfessionalTemporaryJobsRouteImport.update({
    id: '/temporary-jobs',
    path: '/temporary-jobs',
    getParentRoute: () => ProfessionalRoute,
  } as any)
const ProfessionalSpecialtiesRoute = ProfessionalSpecialtiesRouteImport.update({
  id: '/specialties',
  path: '/specialties',
  getParentRoute: () => ProfessionalRoute,
} as any)
const ProfessionalSkillsRoute = ProfessionalSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => ProfessionalRoute,
} as any)
const ProfessionalProfileRoute = ProfessionalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProfessionalRoute,
} as any)
const ProfessionalPermanentJobsRoute =
  ProfessionalPermanentJobsRouteImport.update({
    id: '/permanent-jobs',
    path: '/permanent-jobs',
    getParentRoute: () => ProfessionalRoute,
  } as any)
const ProfessionalJobHistoryRoute = ProfessionalJobHistoryRouteImport.update({
  id: '/job-history',
  path: '/job-history',
  getParentRoute: () => ProfessionalRoute,
} as any)
const ProfessionalDocumentsRoute = ProfessionalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ProfessionalRoute,
} as any)
const ProfessionalCertificatesRoute =
  ProfessionalCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => ProfessionalRoute,
  } as any)
const ProfessionalBannedOfficesRoute =
  ProfessionalBannedOfficesRouteImport.update({
    id: '/banned-offices',
    path: '/banned-offices',
    getParentRoute: () => ProfessionalRoute,
  } as any)
const PracticeStaffRoute = PracticeStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeSettingsRoute = PracticeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeScheduleRoute = PracticeScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticePostingsRoute = PracticePostingsRouteImport.update({
  id: '/postings',
  path: '/postings',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeBillingRoute = PracticeBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PracticeRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRouteWithChildren
  '/professional': typeof ProfessionalRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/practice/billing': typeof PracticeBillingRoute
  '/practice/postings': typeof PracticePostingsRoute
  '/practice/schedule': typeof PracticeScheduleRoute
  '/practice/settings': typeof PracticeSettingsRoute
  '/practice/staff': typeof PracticeStaffRoute
  '/professional/banned-offices': typeof ProfessionalBannedOfficesRoute
  '/professional/certificates': typeof ProfessionalCertificatesRoute
  '/professional/documents': typeof ProfessionalDocumentsRoute
  '/professional/job-history': typeof ProfessionalJobHistoryRoute
  '/professional/permanent-jobs': typeof ProfessionalPermanentJobsRoute
  '/professional/profile': typeof ProfessionalProfileRoute
  '/professional/skills': typeof ProfessionalSkillsRoute
  '/professional/specialties': typeof ProfessionalSpecialtiesRoute
  '/professional/temporary-jobs': typeof ProfessionalTemporaryJobsRoute
  '/admin/': typeof AdminIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/professional/': typeof ProfessionalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/practice/billing': typeof PracticeBillingRoute
  '/practice/postings': typeof PracticePostingsRoute
  '/practice/schedule': typeof PracticeScheduleRoute
  '/practice/settings': typeof PracticeSettingsRoute
  '/practice/staff': typeof PracticeStaffRoute
  '/professional/banned-offices': typeof ProfessionalBannedOfficesRoute
  '/professional/certificates': typeof ProfessionalCertificatesRoute
  '/professional/documents': typeof ProfessionalDocumentsRoute
  '/professional/job-history': typeof ProfessionalJobHistoryRoute
  '/professional/permanent-jobs': typeof ProfessionalPermanentJobsRoute
  '/professional/profile': typeof ProfessionalProfileRoute
  '/professional/skills': typeof ProfessionalSkillsRoute
  '/professional/specialties': typeof ProfessionalSpecialtiesRoute
  '/professional/temporary-jobs': typeof ProfessionalTemporaryJobsRoute
  '/admin': typeof AdminIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/professional': typeof ProfessionalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/practice': typeof PracticeRouteWithChildren
  '/professional': typeof ProfessionalRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/practice/billing': typeof PracticeBillingRoute
  '/practice/postings': typeof PracticePostingsRoute
  '/practice/schedule': typeof PracticeScheduleRoute
  '/practice/settings': typeof PracticeSettingsRoute
  '/practice/staff': typeof PracticeStaffRoute
  '/professional/banned-offices': typeof ProfessionalBannedOfficesRoute
  '/professional/certificates': typeof ProfessionalCertificatesRoute
  '/professional/documents': typeof ProfessionalDocumentsRoute
  '/professional/job-history': typeof ProfessionalJobHistoryRoute
  '/professional/permanent-jobs': typeof ProfessionalPermanentJobsRoute
  '/professional/profile': typeof ProfessionalProfileRoute
  '/professional/skills': typeof ProfessionalSkillsRoute
  '/professional/specialties': typeof ProfessionalSpecialtiesRoute
  '/professional/temporary-jobs': typeof ProfessionalTemporaryJobsRoute
  '/admin/': typeof AdminIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/professional/': typeof ProfessionalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/practice'
    | '/professional'
    | '/admin/reports'
    | '/admin/users'
    | '/practice/billing'
    | '/practice/postings'
    | '/practice/schedule'
    | '/practice/settings'
    | '/practice/staff'
    | '/professional/banned-offices'
    | '/professional/certificates'
    | '/professional/documents'
    | '/professional/job-history'
    | '/professional/permanent-jobs'
    | '/professional/profile'
    | '/professional/skills'
    | '/professional/specialties'
    | '/professional/temporary-jobs'
    | '/admin/'
    | '/practice/'
    | '/professional/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/reports'
    | '/admin/users'
    | '/practice/billing'
    | '/practice/postings'
    | '/practice/schedule'
    | '/practice/settings'
    | '/practice/staff'
    | '/professional/banned-offices'
    | '/professional/certificates'
    | '/professional/documents'
    | '/professional/job-history'
    | '/professional/permanent-jobs'
    | '/professional/profile'
    | '/professional/skills'
    | '/professional/specialties'
    | '/professional/temporary-jobs'
    | '/admin'
    | '/practice'
    | '/professional'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/practice'
    | '/professional'
    | '/admin/reports'
    | '/admin/users'
    | '/practice/billing'
    | '/practice/postings'
    | '/practice/schedule'
    | '/practice/settings'
    | '/practice/staff'
    | '/professional/banned-offices'
    | '/professional/certificates'
    | '/professional/documents'
    | '/professional/job-history'
    | '/professional/permanent-jobs'
    | '/professional/profile'
    | '/professional/skills'
    | '/professional/specialties'
    | '/professional/temporary-jobs'
    | '/admin/'
    | '/practice/'
    | '/professional/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  PracticeRoute: typeof PracticeRouteWithChildren
  ProfessionalRoute: typeof ProfessionalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/professional': {
      id: '/professional'
      path: '/professional'
      fullPath: '/professional'
      preLoaderRoute: typeof ProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional/': {
      id: '/professional/'
      path: '/'
      fullPath: '/professional/'
      preLoaderRoute: typeof ProfessionalIndexRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/practice/': {
      id: '/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/professional/temporary-jobs': {
      id: '/professional/temporary-jobs'
      path: '/temporary-jobs'
      fullPath: '/professional/temporary-jobs'
      preLoaderRoute: typeof ProfessionalTemporaryJobsRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/professional/specialties': {
      id: '/professional/specialties'
      path: '/specialties'
      fullPath: '/professional/specialties'
      preLoaderRoute: typeof ProfessionalSpecialtiesRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/professional/skills': {
      id: '/professional/skills'
      path: '/skills'
      fullPath: '/professional/skills'
      preLoaderRoute: typeof ProfessionalSkillsRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/professional/profile': {
      id: '/professional/profile'
      path: '/profile'
      fullPath: '/professional/profile'
      preLoaderRoute: typeof ProfessionalProfileRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/professional/permanent-jobs': {
      id: '/professional/permanent-jobs'
      path: '/permanent-jobs'
      fullPath: '/professional/permanent-jobs'
      preLoaderRoute: typeof ProfessionalPermanentJobsRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/professional/job-history': {
      id: '/professional/job-history'
      path: '/job-history'
      fullPath: '/professional/job-history'
      preLoaderRoute: typeof ProfessionalJobHistoryRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/professional/documents': {
      id: '/professional/documents'
      path: '/documents'
      fullPath: '/professional/documents'
      preLoaderRoute: typeof ProfessionalDocumentsRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/professional/certificates': {
      id: '/professional/certificates'
      path: '/certificates'
      fullPath: '/professional/certificates'
      preLoaderRoute: typeof ProfessionalCertificatesRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/professional/banned-offices': {
      id: '/professional/banned-offices'
      path: '/banned-offices'
      fullPath: '/professional/banned-offices'
      preLoaderRoute: typeof ProfessionalBannedOfficesRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/practice/staff': {
      id: '/practice/staff'
      path: '/staff'
      fullPath: '/practice/staff'
      preLoaderRoute: typeof PracticeStaffRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/settings': {
      id: '/practice/settings'
      path: '/settings'
      fullPath: '/practice/settings'
      preLoaderRoute: typeof PracticeSettingsRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/schedule': {
      id: '/practice/schedule'
      path: '/schedule'
      fullPath: '/practice/schedule'
      preLoaderRoute: typeof PracticeScheduleRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/postings': {
      id: '/practice/postings'
      path: '/postings'
      fullPath: '/practice/postings'
      preLoaderRoute: typeof PracticePostingsRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/billing': {
      id: '/practice/billing'
      path: '/billing'
      fullPath: '/practice/billing'
      preLoaderRoute: typeof PracticeBillingRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PracticeRouteChildren {
  PracticeBillingRoute: typeof PracticeBillingRoute
  PracticePostingsRoute: typeof PracticePostingsRoute
  PracticeScheduleRoute: typeof PracticeScheduleRoute
  PracticeSettingsRoute: typeof PracticeSettingsRoute
  PracticeStaffRoute: typeof PracticeStaffRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeBillingRoute: PracticeBillingRoute,
  PracticePostingsRoute: PracticePostingsRoute,
  PracticeScheduleRoute: PracticeScheduleRoute,
  PracticeSettingsRoute: PracticeSettingsRoute,
  PracticeStaffRoute: PracticeStaffRoute,
  PracticeIndexRoute: PracticeIndexRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

interface ProfessionalRouteChildren {
  ProfessionalBannedOfficesRoute: typeof ProfessionalBannedOfficesRoute
  ProfessionalCertificatesRoute: typeof ProfessionalCertificatesRoute
  ProfessionalDocumentsRoute: typeof ProfessionalDocumentsRoute
  ProfessionalJobHistoryRoute: typeof ProfessionalJobHistoryRoute
  ProfessionalPermanentJobsRoute: typeof ProfessionalPermanentJobsRoute
  ProfessionalProfileRoute: typeof ProfessionalProfileRoute
  ProfessionalSkillsRoute: typeof ProfessionalSkillsRoute
  ProfessionalSpecialtiesRoute: typeof ProfessionalSpecialtiesRoute
  ProfessionalTemporaryJobsRoute: typeof ProfessionalTemporaryJobsRoute
  ProfessionalIndexRoute: typeof ProfessionalIndexRoute
}

const ProfessionalRouteChildren: ProfessionalRouteChildren = {
  ProfessionalBannedOfficesRoute: ProfessionalBannedOfficesRoute,
  ProfessionalCertificatesRoute: ProfessionalCertificatesRoute,
  ProfessionalDocumentsRoute: ProfessionalDocumentsRoute,
  ProfessionalJobHistoryRoute: ProfessionalJobHistoryRoute,
  ProfessionalPermanentJobsRoute: ProfessionalPermanentJobsRoute,
  ProfessionalProfileRoute: ProfessionalProfileRoute,
  ProfessionalSkillsRoute: ProfessionalSkillsRoute,
  ProfessionalSpecialtiesRoute: ProfessionalSpecialtiesRoute,
  ProfessionalTemporaryJobsRoute: ProfessionalTemporaryJobsRoute,
  ProfessionalIndexRoute: ProfessionalIndexRoute,
}

const ProfessionalRouteWithChildren = ProfessionalRoute._addFileChildren(
  ProfessionalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  PracticeRoute: PracticeRouteWithChildren,
  ProfessionalRoute: ProfessionalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
